### ISSUE TITLE
Could you provide a pre-trained model?

### ISSUE THREAD

**Issue by josh3255** [idnihai/UFATD#1]
Thank you for sharing a good research!

I want to test some video using pre-trained model. could you provide?

**Comment by idnihai** [comment]
Sorry, the paper has not been accepted yet, so I can't share the full content. However, I have updated a model trained on DL-Rail. Please check the README for more details.

**Comment by josh3255** [comment]
@idnihai Additionally, could you provide a demo code?

**Comment by idnihai** [comment]
I have updated the test script.
